### ISSUE TITLE
curious about the 0.01 multiplication for semitones

### ISSUE THREAD

**Issue by x37v** [supercollider-quarks/ScalaTunings#4]
https://github.com/supercollider-quarks/ScalaTunings/blob/84618c6fd58c761ace44e25ca3aaf7acd4a60b7c/ScalaTunings.sc#L44

I'm wondering what that is about?

**Comment by crucialfelix** [comment]
That is odd. I'm not sure that Tim will ever answer though. It's been a long time.

https://github.com/supercollider-quarks/ScalaTunings/blame/84618c6fd58c761ace44e25ca3aaf7acd4a60b7c/ScalaTunings.sc#L44

**Comment by x37v** [comment]
> That is odd. I'm not sure that Tim will ever answer though. It's been a long time.

maybe i'll at @timblechmann to see...

**Comment by timblechmann** [comment]
scala files are using cent, not semitones. compare: https://www.huygens-fokker.org/scala/scl_format.html

**Comment by x37v** [comment]
> scala files are using cent, not semitones. compare: https://www.huygens-fokker.org/scala/scl_format.html

ahh okay, that makes sense now. I should have recognized that as I've done some scala integration myself.. thanks @timblechmann

**Comment by crucialfelix** [comment]
Hi @timblechmann !
